#!/usr/bin/env python3
import os
import sys
import nltk
import helpers

from analyzer import Analyzer
from termcolor import colored
from helpers import get_user_timeline

def main():
    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets screenname")
    
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    # get screen_name's tweets after stripping '@' from screen_name
    tweets = helpers.get_user_timeline(sys.argv[1].lstrip("@"), 50)
    if tweets is None:
        sys.exit("There was an error retrieving tweets.")

    # iterate over each tweet
    for tweet in tweets:
        # analyze each word of tweets, sum up the total score and print each full tweet colored appropriately
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored(tweet, "green"))
        elif score < 0.0:
            print(colored(tweet, "red"))
        else:
            print(colored(tweet, "yellow"))
    
if __name__ == "__main__":
    main()